version: 0.2

phases:
  install:
    runtime-versions:
      java:  openjdk15
  post_build:
    commands:
      - mvn package
      - mv target/laboportal.war laboportal.war
artifacts:
  files:
    - laboportal.war
    - .ebextensions/**/*